version: '3'

services:

    php:
        image: "${PHP_IMAGE_NAME}:${COMPOSE_PROJECT_VERSION}"
        build:
            args:
                php_version: ${PHP_VERSION}
            context: .
            dockerfile: ./build/Dockerfile-php
        container_name: "${COMPOSE_PROJECT_NAME}-php"
        ports:
            - "${PHP_HOST_PORT}:${PHP_CONTAINER_PORT}"
        volumes:
            - ./:/app
        command: "symfony serve --dir=/app/htdocs/public --allow-http --no-tls --port=${PHP_CONTAINER_PORT}"